??# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            小鱼儿
tagline:          My personal website
url:
paginate:         1
author:
  name:           yu
  url:            http://lionxuan888.github.io/
  email:          lionxuan888@gmail.com
comments:
  provider: disqus
  disqus:
    short_name: arsme

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lionxuan888
